name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:


    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [17.4.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ui; npm ci
      - run: cd ui; npm run build --if-present
      - run: export CHROME_BIN=/usr/bin/google-chrome-stable
      - run: cd ui; npm test -- --watch=false --browsers=ChromeHeadless